### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by ismaelcig** [ismaelcig/DAW-project#4]
Arreglar:

- [ ] Evitar collapse al bajar de 751px
- [ ] Fixed-top

BD (Crear tablas):
- [x] Book
- [x] Author
- [x] Genre
- [ ] User

Back-End (Crear clases):
- [ ] Book
- [ ] Author
- [x] Genre
- [ ] User

Front-End:
- [ ] Que al hacer click en los géneros, filtre por el seleccionado
- [ ] Módulo libros

Más:
- [ ] Cargar todos los libros al cargar la página

En un futuro:
- [ ] Ordenar libros/géneros por Top Ventas o algún otro criterio.
- [ ] Mostrar precio en €/$
- [ ] Mostrar textos en ES/EN
